In [1]:
from langchain_openai import ChatOpenAI

In [2]:
llm = ChatOpenAI()

llm.invoke("HOli")

AIMessage(content='Hello! How can I help you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 9, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'id': 'chatcmpl-Den2E1aSioyti7a5jGzLLoRIpzm2o', 'finish_reason': 'stop', 'logprobs': None}, id='run--a45cba37-0b22-4cde-8050-04bb9aa1129f-0', usage_metadata={'input_tokens': 9, 'output_tokens': 9, 'total_tokens': 18, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [3]:
!pip show tsf-rag

Name: tsf-rag
Version: 0.1.0
Summary: AsyncMultiQuery TSF-RAG System for TSF Physical Stability Evaluation
Home-page: https://github.com/GbrlOl/async-multi-query-tsf-rag
Author:
Author-email: Gabriel Olmos <gabriel.olmos@pucv.cl>
License: GPL-3.0-or-later
Location: c:\users\gol_m\anaconda3\envs\paper_geotecnia\lib\site-packages
Editable project location: C:\Users\gol_m\OneDrive\Desktop\eswa
Requires:
Required-by:

# **RAG System Evaluation**

In [1]:
from evaluation_rag import auto_evaluation_rag_v2
from llms_modules import LLMEvaluator

## **1. Naive RAG System Evaluation**

In [2]:
from rag import NaiveRAG

c:\Users\gol_m\anaconda3\envs\paper_geotecnia\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

resource module not available on Windows

### **1.1 Sand Tailing Dams (STD)**

In [3]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 20

OUTPUT_FOLDER = "NaiveRAG_TSF_STD_Evaluation"

PATH_GROUND_TRUTH   = "../src/evaluation_rag/rag_ground_truth/01_STD_Tranque_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/01_cerro_negro_tranque/01_cerro_negro_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CONFIDENCE   = 0.95
OUTPUT_STATS = "NaiveRAG_TSF_STD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = NaiveRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
)
llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 10
Corriendo iteraciones           : 11 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\NaiveRAG_TSF_STD_Evaluation

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:24<02:48, 24.04s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:48<02:24, 24.06s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:56<00:46, 11.61s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [01:03<00:15,  7.71s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:19<00:09,  9.82s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:39<00:00, 12.39s/it]

  ✓ Completada en 99.4s (1.66 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:16<01:52, 16.12s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:28<01:23, 13.89s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:33<00:26,  6.71s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:37<00:09,  4.57s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:53<00:07,  7.50s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.91s/it]

  ✓ Completada en 63.5s (1.06 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:15<01:45, 15.01s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:14, 12.45s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:30<00:24,  6.22s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:37<00:09,  4.88s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:50<00:07,  7.05s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:02<00:00,  7.78s/it]

  ✓ Completada en 62.4s (1.04 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [01:03<07:24, 63.55s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [01:13<03:11, 31.89s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [01:17<00:53, 13.33s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [01:24<00:17,  8.61s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:36<00:09,  9.56s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [02:00<00:00, 15.01s/it]

  ✓ Completada en 120.3s (2.00 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:13<01:34, 13.49s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:14, 12.41s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:31<00:25,  6.49s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:38<00:10,  5.06s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:51<00:07,  7.06s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:00<00:00,  7.53s/it]

  ✓ Completada en 60.4s (1.01 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:16<01:53, 16.15s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:13, 12.30s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:31<00:25,  6.30s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:38<00:09,  4.94s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:50<00:06,  6.73s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:59<00:00,  7.47s/it]

  ✓ Completada en 60.0s (1.00 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:16<01:53, 16.24s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:14, 12.38s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:30<00:24,  6.09s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:36<00:09,  4.65s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:49<00:06,  6.65s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:59<00:00,  7.44s/it]

  ✓ Completada en 59.7s (0.99 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:16<01:58, 16.93s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:27<01:19, 13.25s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:33<00:27,  6.92s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:39<00:09,  4.96s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:52<00:06,  6.92s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:04<00:00,  8.03s/it]

  ✓ Completada en 64.4s (1.07 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:15<01:50, 15.75s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:13, 12.24s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:30<00:24,  6.04s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:35<00:08,  4.49s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:47<00:06,  6.43s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:58<00:00,  7.25s/it]

  ✓ Completada en 58.2s (0.97 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:27<03:15, 27.94s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:37<01:44, 17.41s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:44<00:33,  8.46s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:48<00:11,  5.55s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:00<00:07,  7.01s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.69s/it]

  ✓ Completada en 69.7s (1.16 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:16<01:54, 16.41s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:13, 12.26s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:31<00:25,  6.42s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:37<00:09,  4.80s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:48<00:06,  6.33s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:58<00:00,  7.27s/it]

  ✓ Completada en 58.3s (0.97 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:13<01:36, 13.84s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:24<01:12, 12.12s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:30<00:25,  6.43s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:35<00:09,  4.54s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:47<00:06,  6.44s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:57<00:00,  7.17s/it]

  ✓ Completada en 57.5s (0.96 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:14<01:38, 14.02s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:23<01:08, 11.44s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:28<00:22,  5.72s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:32<00:08,  4.02s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:45<00:06,  6.27s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:54<00:00,  6.85s/it]

  ✓ Completada en 55.0s (0.92 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:18<02:12, 18.93s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:27<01:17, 12.84s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:39<00:34,  8.67s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:11,  5.77s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:56<00:07,  7.21s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:06<00:00,  8.35s/it]

  ✓ Completada en 66.9s (1.12 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:20<02:22, 20.31s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:32<01:34, 15.81s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:39<00:31,  7.97s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:10,  5.28s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:56<00:07,  7.06s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:06<00:00,  8.33s/it]

  ✓ Completada en 66.9s (1.11 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:14<01:42, 14.65s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:27<01:20, 13.34s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:31<00:25,  6.43s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:36<00:09,  4.60s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:47<00:06,  6.18s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:57<00:00,  7.18s/it]

  ✓ Completada en 57.6s (0.96 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:13<01:34, 13.56s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:23<01:08, 11.40s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:32<00:27,  6.95s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:37<00:09,  4.92s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:49<00:06,  6.70s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:58<00:00,  7.36s/it]

  ✓ Completada en 59.1s (0.98 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:14<01:39, 14.22s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:31<01:36, 16.10s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:37<00:31,  7.90s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:43<00:11,  5.57s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:01<00:08,  8.70s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.15s/it]

  ✓ Completada en 73.4s (1.22 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:14<01:41, 14.52s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:34<01:46, 17.80s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:40<00:34,  8.57s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:45<00:11,  5.69s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:04<00:09,  9.11s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:16<00:00,  9.60s/it]

  ✓ Completada en 77.0s (1.28 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:16<01:53, 16.23s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:34<01:44, 17.34s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:38<00:31,  7.88s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:45<00:11,  5.80s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:02<00:08,  8.48s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.89s/it]

  ✓ Completada en 79.3s (1.32 min)

Todas las iteraciones completadas.

In [6]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 10
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,10,50.0,0.00,23.66,76.34
1,Matriz 2,10,60.0,14.06,31.27,83.18
2,Matriz 4,10,100.0,0.00,72.25,100.00
3,Matriz 6,10,100.0,0.00,72.25,100.00
4,Matriz 7,10,35.0,24.15,13.69,64.63
5,Matriz 8,10,100.0,0.00,72.25,100.00
6,Total (matrices evaluadas),10,65.0,7.07,35.37,86.31

✓ Estadísticas exportadas → NaiveRAG_TSF_STD_Statistics.xlsx

In [4]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,50.0,0.00,33.15,66.85
1,Matriz 2,30,60.0,13.56,42.32,75.41
2,Matriz 4,30,100.0,0.00,88.65,100.00
3,Matriz 6,30,100.0,0.00,88.65,100.00
4,Matriz 7,30,20.0,24.91,9.51,37.31
5,Matriz 8,30,100.0,0.00,88.65,100.00
6,Total (matrices evaluadas),30,62.0,6.64,44.23,77.05

✓ Estadísticas exportadas → NaiveRAG_TSF_STD_Statistics.xlsx

### **1.2 Filtered Tailings Deposit (FTD)**

In [4]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "NaiveRAG_TSF_FTD_Evaluation"

PATH_GROUND_TRUTH = "../src/evaluation_rag/rag_ground_truth/02_FTD_Filtrado_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/02_kozan_filtrado/02_kozan_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CONFIDENCE   = 0.95
OUTPUT_STATS = "NaiveRAG_TSF_FTD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = NaiveRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
)
llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\NaiveRAG_TSF_FTD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [02:19<00:00, 17.41s/it]

  ✓ Completada en 139.6s (2.33 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:50<00:00, 13.86s/it]

  ✓ Completada en 111.1s (1.85 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:32<00:00, 11.52s/it]

  ✓ Completada en 92.3s (1.54 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:30<00:00, 11.31s/it]

  ✓ Completada en 90.6s (1.51 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:23<00:00, 10.43s/it]

  ✓ Completada en 83.5s (1.39 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:56<00:00, 14.50s/it]

  ✓ Completada en 116.2s (1.94 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:48<00:00, 13.58s/it]

  ✓ Completada en 108.9s (1.81 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:49<00:00, 13.66s/it]

  ✓ Completada en 109.4s (1.82 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:41<00:00, 12.73s/it]

  ✓ Completada en 101.9s (1.70 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:49<00:00, 13.75s/it]

  ✓ Completada en 110.1s (1.84 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:39<00:00, 12.39s/it]

  ✓ Completada en 99.3s (1.65 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:38<00:00, 12.30s/it]

  ✓ Completada en 98.5s (1.64 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:51<00:00, 14.00s/it]

  ✓ Completada en 112.1s (1.87 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:41<00:00, 12.63s/it]

  ✓ Completada en 101.2s (1.69 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [02:06<00:00, 15.85s/it]

  ✓ Completada en 126.9s (2.12 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:37<00:00, 12.13s/it]

  ✓ Completada en 97.2s (1.62 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:45<00:00, 13.15s/it]

  ✓ Completada en 105.4s (1.76 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:45<00:00, 13.14s/it]

  ✓ Completada en 105.3s (1.75 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [02:21<00:00, 17.70s/it]

  ✓ Completada en 141.8s (2.36 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:38<00:00, 12.34s/it]

  ✓ Completada en 98.8s (1.65 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:35<00:00, 11.95s/it]

  ✓ Completada en 95.7s (1.60 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:31<00:00, 11.47s/it]

  ✓ Completada en 91.9s (1.53 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:25<00:00, 10.65s/it]

  ✓ Completada en 85.3s (1.42 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:43<00:00, 12.92s/it]

  ✓ Completada en 103.5s (1.73 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:32<00:00, 11.55s/it]

  ✓ Completada en 92.6s (1.54 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:35<00:00, 11.98s/it]

  ✓ Completada en 96.0s (1.60 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:28<00:00, 11.01s/it]

  ✓ Completada en 88.2s (1.47 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:36<00:00, 12.00s/it]

  ✓ Completada en 96.2s (1.60 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:38<00:00, 12.33s/it]

  ✓ Completada en 98.8s (1.65 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:42<00:00, 12.77s/it]

  ✓ Completada en 102.3s (1.71 min)

Todas las iteraciones completadas.

In [5]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,29.00,4.03,15.91,46.86
2,Matriz 4,30,100.00,0.00,88.65,100.00
3,Matriz 6,30,100.00,0.00,88.65,100.00
4,Matriz 7,30,36.67,22.49,21.87,54.49
5,Matriz 8,30,100.00,0.00,88.65,100.00
6,Total (matrices evaluadas),30,47.71,3.84,31.14,64.80

✓ Estadísticas exportadas → NaiveRAG_TSF_FTD_Statistics.xlsx

### **1.3 Thickened Tailings Deposit (TTD)**

In [6]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "NaiveRAG_TSF_TTD_Evaluation"

PATH_GROUND_TRUTH = "../src/evaluation_rag/rag_ground_truth/03_TTD_Espesado_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/03_cenizas_espesado/03_cenizas_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CONFIDENCE   = 0.95
OUTPUT_STATS = "NaiveRAG_TSF_TTD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = NaiveRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
)
llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\NaiveRAG_TSF_TTD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:43<00:00, 12.94s/it]

  ✓ Completada en 103.7s (1.73 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:40<00:00, 12.62s/it]

  ✓ Completada en 101.1s (1.69 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:35<00:00, 11.98s/it]

  ✓ Completada en 96.0s (1.60 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:16<00:00,  9.57s/it]

  ✓ Completada en 76.7s (1.28 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:25<00:00, 10.64s/it]

  ✓ Completada en 85.3s (1.42 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:29<00:00, 11.13s/it]

  ✓ Completada en 89.2s (1.49 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.19s/it]

  ✓ Completada en 81.6s (1.36 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:24<00:00, 10.59s/it]

  ✓ Completada en 84.9s (1.41 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.93s/it]

  ✓ Completada en 71.5s (1.19 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.21s/it]

  ✓ Completada en 73.8s (1.23 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.99s/it]

  ✓ Completada en 64.1s (1.07 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.59s/it]

  ✓ Completada en 68.9s (1.15 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:05<00:00,  8.18s/it]

  ✓ Completada en 65.5s (1.09 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.30s/it]

  ✓ Completada en 74.5s (1.24 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.21s/it]

  ✓ Completada en 81.8s (1.36 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.31s/it]

  ✓ Completada en 74.6s (1.24 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.72s/it]

  ✓ Completada en 69.9s (1.16 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.52s/it]

  ✓ Completada en 68.3s (1.14 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.24s/it]

  ✓ Completada en 74.1s (1.23 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 10.92s/it]

  ✓ Completada en 87.5s (1.46 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 10.91s/it]

  ✓ Completada en 87.4s (1.46 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.22s/it]

  ✓ Completada en 73.9s (1.23 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.98s/it]

  ✓ Completada en 72.0s (1.20 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.62s/it]

  ✓ Completada en 69.1s (1.15 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.36s/it]

  ✓ Completada en 75.0s (1.25 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.54s/it]

  ✓ Completada en 68.5s (1.14 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.38s/it]

  ✓ Completada en 67.2s (1.12 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.38s/it]

  ✓ Completada en 67.2s (1.12 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.13s/it]

  ✓ Completada en 73.2s (1.22 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.38s/it]

  ✓ Completada en 67.2s (1.12 min)

Todas las iteraciones completadas.

In [7]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,33.33,0.00,19.23,51.22
2,Matriz 4,30,100.00,0.00,88.65,100.00
3,Matriz 6,30,100.00,0.00,88.65,100.00
4,Matriz 7,30,98.33,9.13,85.87,99.83
5,Matriz 8,30,10.00,30.51,3.46,25.62
6,Total (matrices evaluadas),30,58.89,3.04,41.27,74.49

✓ Estadísticas exportadas → NaiveRAG_TSF_TTD_Statistics.xlsx

### **1.4 Tailing Embankments (TE)**

In [3]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "NaiveRAG_TSF_TE_Evaluation"

PATH_GROUND_TRUTH = "../src/evaluation_rag/rag_ground_truth/04_TE_Embalse_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/04_enami_embalse/04_enami_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CONFIDENCE   = 0.95
OUTPUT_STATS = "NaiveRAG_TSF_TE_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = NaiveRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
)
llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\NaiveRAG_TSF_TE_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:11<01:23, 11.95s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:39<02:05, 20.88s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:46<00:40, 10.15s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:57<00:15,  7.97s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:07<00:08,  8.53s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:17<00:00,  9.63s/it]

  ✓ Completada en 77.3s (1.29 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:35,  5.10s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:26<01:28, 14.68s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:34<00:31,  7.99s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:13,  6.64s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:54<00:07,  7.46s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:04<00:00,  8.02s/it]

  ✓ Completada en 64.3s (1.07 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:38,  5.56s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:31<01:46, 17.78s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:38<00:34,  8.62s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:45<00:12,  6.31s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:01<00:08,  8.69s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.89s/it]

  ✓ Completada en 71.3s (1.19 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:31,  4.54s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:33<01:54, 19.01s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:41<00:38,  9.52s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:47<00:13,  6.52s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:01<00:08,  8.23s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.85s/it]

  ✓ Completada en 71.0s (1.18 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:36,  5.27s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:31<01:45, 17.52s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:37<00:34,  8.54s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:12,  6.12s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:04<00:09,  9.67s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:18<00:00,  9.85s/it]

  ✓ Completada en 78.9s (1.32 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:33,  4.77s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:29<01:38, 16.42s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:37<00:35,  8.80s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:46<00:13,  6.68s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:57<00:07,  7.82s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.68s/it]

  ✓ Completada en 69.6s (1.16 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:07<00:52,  7.48s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:34<01:53, 18.90s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:40<00:35,  8.97s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:54<00:16,  8.15s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:09<00:09,  9.75s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.96s/it]

  ✓ Completada en 79.8s (1.33 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:32,  4.66s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:38<02:10, 21.68s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:44<00:40, 10.19s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:57<00:16,  8.26s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:11<00:09,  9.74s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.25s/it]

  ✓ Completada en 82.2s (1.37 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:36,  5.20s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:34<01:54, 19.11s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:40<00:37,  9.28s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:50<00:14,  7.17s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:03<00:08,  8.57s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.06s/it]

  ✓ Completada en 72.6s (1.21 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:37,  5.30s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:35<01:59, 19.91s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:42<00:38,  9.66s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:54<00:16,  8.01s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:08<00:09,  9.32s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:17<00:00,  9.73s/it]

  ✓ Completada en 78.0s (1.30 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:36,  5.20s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:24<01:21, 13.62s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:33<00:31,  7.91s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:46<00:14,  7.24s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:58<00:08,  8.40s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.91s/it]

  ✓ Completada en 71.4s (1.19 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:38,  5.48s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:31<01:44, 17.48s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:39<00:36,  9.01s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:59<00:18,  9.43s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:17<00:11, 11.61s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:26<00:00, 10.86s/it]

  ✓ Completada en 87.1s (1.45 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:36,  5.16s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:24<01:21, 13.65s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:33<00:31,  7.80s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:45<00:14,  7.06s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:58<00:08,  8.37s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.73s/it]

  ✓ Completada en 70.0s (1.17 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:06<00:46,  6.64s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:27<01:28, 14.74s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:34<00:30,  7.72s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:12,  6.50s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:56<00:07,  7.95s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:05<00:00,  8.24s/it]

  ✓ Completada en 66.1s (1.10 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:31,  4.54s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:26<01:30, 15.01s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:34<00:31,  7.99s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:46<00:14,  7.12s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:58<00:08,  8.26s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.51s/it]

  ✓ Completada en 68.2s (1.14 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:06<00:44,  6.39s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:22<01:13, 12.26s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:42<00:43, 10.86s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:55<00:17,  8.62s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:06<00:09,  9.27s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.29s/it]

  ✓ Completada en 82.5s (1.38 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:34,  4.98s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:24, 14.07s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:32<00:29,  7.43s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:13,  6.80s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [01:00<00:09,  9.08s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.64s/it]

  ✓ Completada en 69.3s (1.15 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:34,  4.91s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:19<01:03, 10.56s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:26<00:24,  6.17s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:38<00:12,  6.04s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:52<00:08,  8.09s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:01<00:00,  7.74s/it]

  ✓ Completada en 62.1s (1.04 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:35,  5.11s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:23<01:16, 12.71s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:31<00:28,  7.24s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:44<00:13,  6.93s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:56<00:08,  8.15s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.97s/it]

  ✓ Completada en 64.0s (1.07 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:32,  4.62s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:21<01:09, 11.66s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:28<00:26,  6.64s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:39<00:12,  6.15s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:49<00:07,  7.16s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:57<00:00,  7.22s/it]

  ✓ Completada en 58.0s (0.97 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:34,  4.94s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:22<01:13, 12.18s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:29<00:27,  6.89s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:42<00:13,  6.69s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:53<00:07,  7.82s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:01<00:00,  7.66s/it]

  ✓ Completada en 61.5s (1.02 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:33,  4.84s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:19<01:03, 10.61s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:26<00:24,  6.19s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:37<00:11,  5.84s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:48<00:07,  7.18s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:56<00:00,  7.06s/it]

  ✓ Completada en 56.6s (0.94 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:38,  5.54s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:19<01:04, 10.71s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:27<00:24,  6.25s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:42<00:13,  6.99s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:52<00:07,  7.72s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:01<00:00,  7.65s/it]

  ✓ Completada en 61.4s (1.02 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:07<00:52,  7.56s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:25<01:21, 13.55s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:32<00:28,  7.22s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:41<00:12,  6.07s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:53<00:07,  7.58s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:01<00:00,  7.72s/it]

  ✓ Completada en 61.9s (1.03 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:35,  5.12s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:24<01:22, 13.79s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:31<00:28,  7.10s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:42<00:12,  6.40s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:52<00:07,  7.34s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [01:01<00:00,  7.64s/it]

  ✓ Completada en 61.2s (1.02 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:32,  4.68s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:21<01:12, 12.04s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:29<00:27,  6.95s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:36<00:10,  5.32s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:47<00:06,  6.70s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:56<00:00,  7.12s/it]

  ✓ Completada en 57.1s (0.95 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:31,  4.52s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:18<00:59, 10.00s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:24<00:22,  5.69s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:31<00:09,  4.60s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:42<00:06,  6.27s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:49<00:00,  6.20s/it]

  ✓ Completada en 49.8s (0.83 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:29,  4.22s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:18<01:01, 10.25s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:25<00:23,  5.88s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:34<00:10,  5.35s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:46<00:06,  6.84s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:54<00:00,  6.87s/it]

  ✓ Completada en 55.1s (0.92 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:04<00:32,  4.61s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:23<01:18, 13.14s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:30<00:27,  6.91s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:40<00:12,  6.10s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:50<00:07,  7.06s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:57<00:00,  7.18s/it]

  ✓ Completada en 57.6s (0.96 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1

Evaluación Matriz:  12%|█▎        | 1/8 [00:05<00:36,  5.20s/it]

Matriz 2

Evaluación Matriz:  25%|██▌       | 2/8 [00:20<01:05, 10.85s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4

Evaluación Matriz:  50%|█████     | 4/8 [00:27<00:25,  6.31s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6

Evaluación Matriz:  75%|███████▌  | 6/8 [00:37<00:11,  5.77s/it]

Matriz 7

Evaluación Matriz:  88%|████████▊ | 7/8 [00:48<00:07,  7.17s/it]

Matriz 8

Evaluación Matriz: 100%|██████████| 8/8 [00:56<00:00,  7.07s/it]

  ✓ Completada en 56.7s (0.95 min)

Todas las iteraciones completadas.

In [4]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,0.0,0.0,0.00,11.35
1,Matriz 2,30,75.0,0.0,57.30,87.02
2,Matriz 4,30,100.0,0.0,88.65,100.00
3,Matriz 6,30,0.0,0.0,0.00,11.35
4,Matriz 7,30,50.0,0.0,33.15,66.85
5,Matriz 8,30,100.0,0.0,88.65,100.00
6,Total (matrices evaluadas),30,60.0,0.0,42.32,75.41

✓ Estadísticas exportadas → NaiveRAG_TSF_TE_Statistics.xlsx

### **1.5 Paste Tailings Deposits (PTD)**

In [3]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "NaiveRAG_TSF_PTD_Evaluation"

PATH_GROUND_TRUTH = "../src/evaluation_rag/rag_ground_truth/05_PTD_EnPasta_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/05_florida_pasta/05_florida_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CONFIDENCE   = 0.95
OUTPUT_STATS = "NaiveRAG_TSF_PTD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = NaiveRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
)
llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\NaiveRAG_TSF_PTD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [02:20<00:00, 17.51s/it]

  ✓ Completada en 140.4s (2.34 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:45<00:00, 13.16s/it]

  ✓ Completada en 105.5s (1.76 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [02:00<00:00, 15.03s/it]

  ✓ Completada en 120.4s (2.01 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:44<00:00, 13.12s/it]

  ✓ Completada en 105.1s (1.75 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:26<00:00, 10.86s/it]

  ✓ Completada en 87.1s (1.45 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.96s/it]

  ✓ Completada en 63.8s (1.06 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.68s/it]

  ✓ Completada en 69.6s (1.16 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.21s/it]

  ✓ Completada en 81.8s (1.36 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.98s/it]

  ✓ Completada en 72.0s (1.20 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:02<00:00,  7.84s/it]

  ✓ Completada en 62.8s (1.05 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.01s/it]

  ✓ Completada en 72.2s (1.20 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.33s/it]

  ✓ Completada en 74.8s (1.25 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.41s/it]

  ✓ Completada en 67.5s (1.12 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:05<00:00,  8.25s/it]

  ✓ Completada en 66.2s (1.10 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:06<00:00,  8.34s/it]

  ✓ Completada en 66.8s (1.11 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.89s/it]

  ✓ Completada en 71.3s (1.19 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.86s/it]

  ✓ Completada en 71.0s (1.18 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.01s/it]

  ✓ Completada en 72.3s (1.20 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.74s/it]

  ✓ Completada en 70.1s (1.17 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.12s/it]

  ✓ Completada en 73.1s (1.22 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.69s/it]

  ✓ Completada en 69.7s (1.16 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.25s/it]

  ✓ Completada en 82.2s (1.37 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:33<00:00, 11.71s/it]

  ✓ Completada en 93.9s (1.56 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:30<00:00, 11.37s/it]

  ✓ Completada en 91.1s (1.52 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.94s/it]

  ✓ Completada en 79.7s (1.33 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.22s/it]

  ✓ Completada en 73.9s (1.23 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 10.98s/it]

  ✓ Completada en 88.0s (1.47 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:24<00:00, 10.59s/it]

  ✓ Completada en 84.9s (1.42 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.86s/it]

  ✓ Completada en 71.1s (1.18 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.85s/it]

  ✓ Completada en 70.9s (1.18 min)

Todas las iteraciones completadas.

In [4]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,47.78,5.76,31.20,64.86
2,Matriz 4,30,100.00,0.00,88.65,100.00
3,Matriz 6,30,96.67,18.26,83.33,99.41
4,Matriz 7,30,50.00,0.00,33.15,66.85
5,Matriz 8,30,100.00,0.00,88.65,100.00
6,Total (matrices evaluadas),30,65.28,3.84,47.41,79.68

✓ Estadísticas exportadas → NaiveRAG_TSF_PTD_Statistics.xlsx

## **2. Advanced RAG System Evaluation**

In [2]:
from rag import AdvancedRAG

c:\Users\gol_m\anaconda3\envs\paper_geotecnia\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

resource module not available on Windows

### **2.1 Sand Tailing Dams (STD)**

In [3]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "02_AdvancedRAG_TSF_STD_Evaluation"

PATH_GROUND_TRUTH   = "../src/evaluation_rag/rag_ground_truth/01_STD_Tranque_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/01_cerro_negro_tranque/01_cerro_negro_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CROSS_ENCODER_MODEL_NAME="cross-encoder/ms-marco-MiniLM-L-6-v2"
TOP_N = 5

CONFIDENCE   = 0.95
OUTPUT_STATS = "02_AdvancedRAG_TSF_STD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = AdvancedRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
    cross_encoder_model_name=CROSS_ENCODER_MODEL_NAME,
    top_n=TOP_N
)

llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\02_AdvancedRAG_TSF_STD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:42<00:00, 12.80s/it]

  ✓ Completada en 102.6s (1.71 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:15<00:00,  9.46s/it]

  ✓ Completada en 75.8s (1.26 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:17<00:00,  9.66s/it]

  ✓ Completada en 77.5s (1.29 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 10.98s/it]

  ✓ Completada en 88.0s (1.47 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:24<00:00, 10.58s/it]

  ✓ Completada en 84.8s (1.41 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:16<00:00,  9.60s/it]

  ✓ Completada en 77.0s (1.28 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:26<00:00, 10.79s/it]

  ✓ Completada en 86.5s (1.44 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.29s/it]

  ✓ Completada en 82.4s (1.37 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:15<00:00,  9.48s/it]

  ✓ Completada en 76.0s (1.27 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.34s/it]

  ✓ Completada en 82.9s (1.38 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:25<00:00, 10.73s/it]

  ✓ Completada en 86.0s (1.43 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.29s/it]

  ✓ Completada en 82.5s (1.38 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.15s/it]

  ✓ Completada en 81.4s (1.36 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:33<00:00, 11.72s/it]

  ✓ Completada en 93.9s (1.56 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:26<00:00, 10.86s/it]

  ✓ Completada en 87.0s (1.45 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:15<00:00,  9.39s/it]

  ✓ Completada en 75.3s (1.25 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.34s/it]

  ✓ Completada en 74.9s (1.25 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 10.88s/it]

  ✓ Completada en 87.2s (1.45 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 10.92s/it]

  ✓ Completada en 87.5s (1.46 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:23<00:00, 10.46s/it]

  ✓ Completada en 83.8s (1.40 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.13s/it]

  ✓ Completada en 81.2s (1.35 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:39<00:00, 12.46s/it]

  ✓ Completada en 99.9s (1.66 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:33<00:00, 11.69s/it]

  ✓ Completada en 93.7s (1.56 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.32s/it]

  ✓ Completada en 82.7s (1.38 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.96s/it]

  ✓ Completada en 79.8s (1.33 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.25s/it]

  ✓ Completada en 82.2s (1.37 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:17<00:00,  9.70s/it]

  ✓ Completada en 77.8s (1.30 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.13s/it]

  ✓ Completada en 81.1s (1.35 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:23<00:00, 10.44s/it]

  ✓ Completada en 83.7s (1.39 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:17<00:00,  9.63s/it]

  ✓ Completada en 77.2s (1.29 min)

Todas las iteraciones completadas.

In [4]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,50.00,0.00,33.15,66.85
1,Matriz 2,30,33.33,0.00,19.23,51.22
2,Matriz 4,30,73.33,44.98,55.55,85.82
3,Matriz 6,30,100.00,0.00,88.65,100.00
4,Matriz 7,30,41.67,18.95,25.98,59.25
5,Matriz 8,30,96.67,18.26,83.33,99.41
6,Total (matrices evaluadas),30,55.33,5.07,37.97,71.49

✓ Estadísticas exportadas → 02_AdvancedRAG_TSF_STD_Statistics.xlsx

### **2.2 Filtered Tailings Deposit (FTD)**

In [5]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "02_AdvancedRAG_TSF_FTD_Evaluation"

PATH_GROUND_TRUTH   = "../src/evaluation_rag/rag_ground_truth/02_FTD_Filtrado_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/02_kozan_filtrado/02_kozan_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CROSS_ENCODER_MODEL_NAME="cross-encoder/ms-marco-MiniLM-L-6-v2"
TOP_N = 5

CONFIDENCE   = 0.95
OUTPUT_STATS = "02_AdvancedRAG_TSF_FTD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = AdvancedRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
    cross_encoder_model_name=CROSS_ENCODER_MODEL_NAME,
    top_n=TOP_N
)

llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\02_AdvancedRAG_TSF_FTD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:58<00:00, 14.87s/it]

  ✓ Completada en 119.2s (1.99 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:51<00:00, 13.90s/it]

  ✓ Completada en 111.4s (1.86 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:49<00:00, 13.63s/it]

  ✓ Completada en 109.2s (1.82 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:30<00:00, 11.29s/it]

  ✓ Completada en 90.5s (1.51 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:39<00:00, 12.46s/it]

  ✓ Completada en 99.8s (1.66 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:53<00:00, 14.22s/it]

  ✓ Completada en 113.9s (1.90 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:35<00:00, 12.00s/it]

  ✓ Completada en 96.1s (1.60 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:31<00:00, 11.49s/it]

  ✓ Completada en 92.0s (1.53 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:43<00:00, 12.91s/it]

  ✓ Completada en 103.5s (1.72 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:37<00:00, 12.20s/it]

  ✓ Completada en 97.7s (1.63 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:43<00:00, 12.90s/it]

  ✓ Completada en 103.3s (1.72 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:34<00:00, 11.82s/it]

  ✓ Completada en 94.7s (1.58 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:43<00:00, 12.92s/it]

  ✓ Completada en 103.5s (1.72 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:38<00:00, 12.36s/it]

  ✓ Completada en 99.1s (1.65 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:41<00:00, 12.70s/it]

  ✓ Completada en 101.8s (1.70 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:32<00:00, 11.50s/it]

  ✓ Completada en 92.2s (1.54 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:33<00:00, 11.74s/it]

  ✓ Completada en 94.1s (1.57 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:32<00:00, 11.61s/it]

  ✓ Completada en 93.0s (1.55 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:34<00:00, 11.78s/it]

  ✓ Completada en 94.4s (1.57 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:36<00:00, 12.10s/it]

  ✓ Completada en 97.0s (1.62 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:29<00:00, 11.16s/it]

  ✓ Completada en 89.5s (1.49 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:42<00:00, 12.87s/it]

  ✓ Completada en 103.1s (1.72 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:46<00:00, 13.31s/it]

  ✓ Completada en 106.7s (1.78 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:55<00:00, 14.38s/it]

  ✓ Completada en 115.2s (1.92 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:37<00:00, 12.13s/it]

  ✓ Completada en 97.2s (1.62 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:40<00:00, 12.54s/it]

  ✓ Completada en 100.5s (1.67 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:43<00:00, 12.95s/it]

  ✓ Completada en 103.7s (1.73 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:34<00:00, 11.79s/it]

  ✓ Completada en 94.4s (1.57 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:31<00:00, 11.50s/it]

  ✓ Completada en 92.1s (1.54 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:36<00:00, 12.02s/it]

  ✓ Completada en 96.3s (1.60 min)

Todas las iteraciones completadas.

In [6]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,29.33,2.54,16.16,47.20
2,Matriz 4,30,0.00,0.00,0.00,11.35
3,Matriz 6,30,100.00,0.00,88.65,100.00
4,Matriz 7,30,50.00,0.00,33.15,66.85
5,Matriz 8,30,36.67,49.01,21.87,54.49
6,Total (matrices evaluadas),30,39.38,3.34,24.08,57.09

✓ Estadísticas exportadas → 02_AdvancedRAG_TSF_FTD_Statistics.xlsx

### **2.3 Thickened Tailings Deposit (TTD)**

In [7]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "02_AdvancedRAG_TSF_TTD_Evaluation"

PATH_GROUND_TRUTH   = "../src/evaluation_rag/rag_ground_truth/03_TTD_Espesado_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/03_cenizas_espesado/03_cenizas_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CROSS_ENCODER_MODEL_NAME="cross-encoder/ms-marco-MiniLM-L-6-v2"
TOP_N = 5

CONFIDENCE   = 0.95
OUTPUT_STATS = "02_AdvancedRAG_TSF_TTD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = AdvancedRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
    cross_encoder_model_name=CROSS_ENCODER_MODEL_NAME,
    top_n=TOP_N
)

llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\02_AdvancedRAG_TSF_TTD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.20s/it]

  ✓ Completada en 81.8s (1.36 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:27<00:00, 11.00s/it]

  ✓ Completada en 88.2s (1.47 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:36<00:00, 12.10s/it]

  ✓ Completada en 97.0s (1.62 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.97s/it]

  ✓ Completada en 79.9s (1.33 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.13s/it]

  ✓ Completada en 73.2s (1.22 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:29<00:00, 11.17s/it]

  ✓ Completada en 89.5s (1.49 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:23<00:00, 10.38s/it]

  ✓ Completada en 83.2s (1.39 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.99s/it]

  ✓ Completada en 80.0s (1.33 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:55<00:00, 14.43s/it]

  ✓ Completada en 115.6s (1.93 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.91s/it]

  ✓ Completada en 79.4s (1.32 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.90s/it]

  ✓ Completada en 79.3s (1.32 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:15<00:00,  9.43s/it]

  ✓ Completada en 75.6s (1.26 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.13s/it]

  ✓ Completada en 73.2s (1.22 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.11s/it]

  ✓ Completada en 73.0s (1.22 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:29<00:00, 11.15s/it]

  ✓ Completada en 89.3s (1.49 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.86s/it]

  ✓ Completada en 71.1s (1.18 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.36s/it]

  ✓ Completada en 75.0s (1.25 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.31s/it]

  ✓ Completada en 74.6s (1.24 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.97s/it]

  ✓ Completada en 79.9s (1.33 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.02s/it]

  ✓ Completada en 72.3s (1.20 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:24<00:00, 10.53s/it]

  ✓ Completada en 84.4s (1.41 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:20<00:00, 10.07s/it]

  ✓ Completada en 80.7s (1.35 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.76s/it]

  ✓ Completada en 70.2s (1.17 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.37s/it]

  ✓ Completada en 75.2s (1.25 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.03s/it]

  ✓ Completada en 72.4s (1.21 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:18<00:00,  9.78s/it]

  ✓ Completada en 78.4s (1.31 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.24s/it]

  ✓ Completada en 82.1s (1.37 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.54s/it]

  ✓ Completada en 68.5s (1.14 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.15s/it]

  ✓ Completada en 73.4s (1.22 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.07s/it]

  ✓ Completada en 72.8s (1.21 min)

Todas las iteraciones completadas.

In [8]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,38.33,7.77,23.22,56.09
2,Matriz 4,30,100.00,0.00,88.65,100.00
3,Matriz 6,30,100.00,0.00,88.65,100.00
4,Matriz 7,30,100.00,0.00,88.65,100.00
5,Matriz 8,30,50.00,50.85,33.15,66.85
6,Total (matrices evaluadas),30,65.00,5.54,47.14,79.46

✓ Estadísticas exportadas → 02_AdvancedRAG_TSF_TTD_Statistics.xlsx

### **2.4 Tailings Embankments (TE)**

In [9]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "02_AdvancedRAG_TSF_TE_Evaluation"

PATH_GROUND_TRUTH   = "../src/evaluation_rag/rag_ground_truth/04_TE_Embalse_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/04_enami_embalse/04_enami_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CROSS_ENCODER_MODEL_NAME="cross-encoder/ms-marco-MiniLM-L-6-v2"
TOP_N = 5

CONFIDENCE   = 0.95
OUTPUT_STATS = "02_AdvancedRAG_TSF_TE_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = AdvancedRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
    cross_encoder_model_name=CROSS_ENCODER_MODEL_NAME,
    top_n=TOP_N
)

llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\02_AdvancedRAG_TSF_TE_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:06<00:00,  8.32s/it]

  ✓ Completada en 66.8s (1.11 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:05<00:00,  8.16s/it]

  ✓ Completada en 65.5s (1.09 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:10<00:00,  8.87s/it]

  ✓ Completada en 71.1s (1.18 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.18s/it]

  ✓ Completada en 73.6s (1.23 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:04<00:00,  8.10s/it]

  ✓ Completada en 65.0s (1.08 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.49s/it]

  ✓ Completada en 68.1s (1.13 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.65s/it]

  ✓ Completada en 69.3s (1.16 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.43s/it]

  ✓ Completada en 67.6s (1.13 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:06<00:00,  8.32s/it]

  ✓ Completada en 66.8s (1.11 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:15<00:00,  9.44s/it]

  ✓ Completada en 75.7s (1.26 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:01<00:00,  7.71s/it]

  ✓ Completada en 61.8s (1.03 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.39s/it]

  ✓ Completada en 67.3s (1.12 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.63s/it]

  ✓ Completada en 69.2s (1.15 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:02<00:00,  7.79s/it]

  ✓ Completada en 62.4s (1.04 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:14<00:00,  9.33s/it]

  ✓ Completada en 74.8s (1.25 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:00<00:00,  7.59s/it]

  ✓ Completada en 60.8s (1.01 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:02<00:00,  7.83s/it]

  ✓ Completada en 62.8s (1.05 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.90s/it]

  ✓ Completada en 63.3s (1.06 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.98s/it]

  ✓ Completada en 64.0s (1.07 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:00<00:00,  7.61s/it]

  ✓ Completada en 61.0s (1.02 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.90s/it]

  ✓ Completada en 71.3s (1.19 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:00<00:00,  7.60s/it]

  ✓ Completada en 61.0s (1.02 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.88s/it]

  ✓ Completada en 63.2s (1.05 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.89s/it]

  ✓ Completada en 63.2s (1.05 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:04<00:00,  8.01s/it]

  ✓ Completada en 64.2s (1.07 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.39s/it]

  ✓ Completada en 67.3s (1.12 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:04<00:00,  8.10s/it]

  ✓ Completada en 64.9s (1.08 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:06<00:00,  8.35s/it]

  ✓ Completada en 66.9s (1.12 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:03<00:00,  7.97s/it]

  ✓ Completada en 63.9s (1.07 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:04<00:00,  8.03s/it]

  ✓ Completada en 64.4s (1.07 min)

Todas las iteraciones completadas.

In [10]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.0,0.0,88.65,100.00
1,Matriz 2,30,75.0,0.0,57.30,87.02
2,Matriz 4,30,100.0,0.0,88.65,100.00
3,Matriz 6,30,0.0,0.0,0.00,11.35
4,Matriz 7,30,50.0,0.0,33.15,66.85
5,Matriz 8,30,100.0,0.0,88.65,100.00
6,Total (matrices evaluadas),30,70.0,0.0,52.12,83.34

✓ Estadísticas exportadas → 02_AdvancedRAG_TSF_TE_Statistics.xlsx

### **2.5 Paste Tailings Deposits (PTD)**

In [11]:
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

N_ITERATIONS = 30

OUTPUT_FOLDER = "02_AdvancedRAG_TSF_PTD_Evaluation"

PATH_GROUND_TRUTH   = "../src/evaluation_rag/rag_ground_truth/05_PTD_EnPasta_GT.xlsx"
PATH_VECTOR_STORAGE = "../src/evaluation_retrieval/vector_storage/05_florida_pasta/05_florida_nomic"
EMBEDDING_TYPE      = "nomic"
EMBEDDING_MODEL     = "nomic-embed-text-v1.5"

CROSS_ENCODER_MODEL_NAME="cross-encoder/ms-marco-MiniLM-L-6-v2"
TOP_N = 5

CONFIDENCE   = 0.95
OUTPUT_STATS = "02_AdvancedRAG_TSF_PTD_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

pipeline_rag = AdvancedRAG(
    path_vector_storage=PATH_VECTOR_STORAGE,
    embedding_type=EMBEDDING_TYPE,
    embedding_model_name=EMBEDDING_MODEL,
    cross_encoder_model_name=CROSS_ENCODER_MODEL_NAME,
    top_n=TOP_N
)

llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 0
Corriendo iteraciones           : 1 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\02_AdvancedRAG_TSF_PTD_Evaluation

=======================================================
  Iteración 001 de 030 → iteration_001.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.88s/it]

  ✓ Completada en 79.3s (1.32 min)

=======================================================
  Iteración 002 de 030 → iteration_002.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.54s/it]

  ✓ Completada en 68.5s (1.14 min)

=======================================================
  Iteración 003 de 030 → iteration_003.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:19<00:00,  9.94s/it]

  ✓ Completada en 79.7s (1.33 min)

=======================================================
  Iteración 004 de 030 → iteration_004.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.91s/it]

  ✓ Completada en 71.4s (1.19 min)

=======================================================
  Iteración 005 de 030 → iteration_005.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.45s/it]

  ✓ Completada en 67.8s (1.13 min)

=======================================================
  Iteración 006 de 030 → iteration_006.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.57s/it]

  ✓ Completada en 68.7s (1.15 min)

=======================================================
  Iteración 007 de 030 → iteration_007.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.54s/it]

  ✓ Completada en 68.5s (1.14 min)

=======================================================
  Iteración 008 de 030 → iteration_008.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.11s/it]

  ✓ Completada en 73.0s (1.22 min)

=======================================================
  Iteración 009 de 030 → iteration_009.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.96s/it]

  ✓ Completada en 71.8s (1.20 min)

=======================================================
  Iteración 010 de 030 → iteration_010.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.59s/it]

  ✓ Completada en 68.8s (1.15 min)

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.24s/it]

  ✓ Completada en 74.1s (1.23 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.62s/it]

  ✓ Completada en 69.1s (1.15 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.69s/it]

  ✓ Completada en 69.6s (1.16 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:29<00:00, 11.21s/it]

  ✓ Completada en 89.9s (1.50 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.99s/it]

  ✓ Completada en 72.0s (1.20 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.21s/it]

  ✓ Completada en 73.8s (1.23 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:18<00:00,  9.84s/it]

  ✓ Completada en 78.9s (1.31 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.91s/it]

  ✓ Completada en 71.4s (1.19 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:07<00:00,  8.47s/it]

  ✓ Completada en 67.9s (1.13 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:12<00:00,  9.08s/it]

  ✓ Completada en 72.8s (1.21 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:08<00:00,  8.52s/it]

  ✓ Completada en 68.3s (1.14 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:11<00:00,  8.89s/it]

  ✓ Completada en 71.3s (1.19 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:09<00:00,  8.75s/it]

  ✓ Completada en 70.1s (1.17 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:13<00:00,  9.13s/it]

  ✓ Completada en 73.2s (1.22 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:22<00:00, 10.31s/it]

  ✓ Completada en 82.6s (1.38 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:32<00:00, 11.55s/it]

  ✓ Completada en 92.5s (1.54 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:30<00:00, 11.29s/it]

  ✓ Completada en 90.5s (1.51 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:21<00:00, 10.19s/it]

  ✓ Completada en 81.7s (1.36 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [01:36<00:00, 12.05s/it]

  ✓ Completada en 96.6s (1.61 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz: 100%|██████████| 8/8 [04:00<00:00, 30.07s/it]

  ✓ Completada en 240.7s (4.01 min)

Todas las iteraciones completadas.

In [12]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

# Cargar todas las iteraciones
iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

# Construir DataFrame de detalle
all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

# Calcular estadísticas por matriz
stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

# Formatear detalle como porcentajes legibles
df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

# Mostrar en notebook
print("\nEstadísticas por matriz:")
display(df_stats)

# Exportar Excel
with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,56.67,8.31,39.20,72.62
2,Matriz 4,30,100.00,0.00,88.65,100.00
3,Matriz 6,30,13.33,34.57,5.31,29.68
4,Matriz 7,30,50.00,0.00,33.15,66.85
5,Matriz 8,30,100.00,0.00,88.65,100.00
6,Total (matrices evaluadas),30,62.78,5.68,44.98,77.68

✓ Estadísticas exportadas → 02_AdvancedRAG_TSF_PTD_Statistics.xlsx

## **3. Hybrid RAG System Evaluation**

In [ ]:
from rag import HybridRAG

### **3.1 Sand Tailing Dams (STD)**

### **3.2 Filtered Tailings Deposit (FTD)**

### **3.3 Thickened Tailings Deposit (TTD)**

### **3.4 Tailings Embankments (TE)**

### **3.5 Paste Tailings Deposits (PTD)**

## **5. AsyncMultiQuery RAG System Evaluation**

In [1]:
from utils import EmbeddingConfig, AsyncMultiEmbeddingRAGV2
import os
import re
import time
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats
from llms_modules import LLMEvaluator
from evaluation_rag import auto_evaluation_rag_v2

resource module not available on Windows

c:\Users\gol_m\anaconda3\envs\paper_geotecnia\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### **1.1 Sand Tailing Dams (STD)**

In [2]:
N_ITERATIONS = 20

OUTPUT_FOLDER = "AsyncMultiQuery_TSF_STD_Evaluation"

PATH_GROUND_TRUTH = "../src/evaluation_rag/rag_ground_truth/01_STD_Tranque_GT.xlsx"

CONFIDENCE   = 0.95
OUTPUT_STATS = "AsyncMultiQuery_TSF_STD_Statistics.xlsx"

In [3]:
def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

In [4]:
embedding_configs = [
    EmbeddingConfig(
        name="minilm",
        embedding_type="huggingface",
        model_name="sentence-transformers/all-MiniLM-L6-v2",
        path_vector_storage="../src/evaluation_retrieval/vector_storage/01_cerro_negro_tranque/01_cerro_negro_all_mini_L6_v2"
    ),
    EmbeddingConfig(
        name="nomic",
        embedding_type="nomic",
        model_name="nomic-embed-text-v1.5",
        path_vector_storage="../src/evaluation_retrieval/vector_storage/01_cerro_negro_tranque/01_cerro_negro_nomic"
    )
]

pipeline_rag = AsyncMultiEmbeddingRAGV2(
    embedding_configs=embedding_configs,
    top_k=13,
    top_n=5
)

llm_evaluador = LLMEvaluator()

Configurando modelos de embeddings e índices...
Configurando embedding: minilm
✓ Embedding minilm configurado correctamente
Configurando embedding: nomic
✓ Embedding nomic configurado correctamente
Cargando Cross-Encoder...

In [5]:
folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Iteraciones previas encontradas : 10
Corriendo iteraciones           : 11 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\AsyncMultiQuery_TSF_STD_Evaluation

=======================================================
  Iteración 011 de 030 → iteration_011.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:02<00:00,  1.26s/it]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.42it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [01:09<08:04, 69.24s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.00it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.74it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:24<07:15, 72.51s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.01it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:52<02:23, 35.85s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.65it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 34

Evaluación Matriz:  75%|███████▌  | 6/8 [03:18<00:50, 25.24s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.46it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

Procesando embeddings:  50%|█████     | 1/2 [00:00<00:00,  7.29it/s]

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.68it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Evaluación Matriz:  88%|████████▊ | 7/8 [04:21<00:34, 34.66s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.27it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 49

Evaluación Matriz: 100%|██████████| 8/8 [05:10<00:00, 38.79s/it]

  ✓ Completada en 310.6s (5.18 min)

=======================================================
  Iteración 012 de 030 → iteration_012.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

Procesando embeddings:  50%|█████     | 1/2 [00:00<00:00,  6.41it/s]

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.18it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.90it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [01:07<07:55, 67.97s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.61it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.25it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:19<07:01, 70.31s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:01<00:00,  1.42it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:45<02:17, 34.29s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.08it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [03:11<00:48, 24.09s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.17it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.08it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz:  88%|████████▊ | 7/8 [04:30<00:38, 38.02s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.84it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:05<00:00, 38.20s/it]

  ✓ Completada en 305.8s (5.10 min)

=======================================================
  Iteración 013 de 030 → iteration_013.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.05it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.29it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [00:55<06:27, 55.32s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.46it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.02it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.90it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:09<06:40, 66.67s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.56it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:39<02:16, 34.23s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.25it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [03:13<00:52, 26.05s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.38it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.74it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [04:10<00:33, 33.72s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.26it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:49<00:00, 36.20s/it]

  ✓ Completada en 289.9s (4.83 min)

=======================================================
  Iteración 014 de 030 → iteration_014.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm
✓ Retrieval completado para embedding: nomic

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.46it/s]

Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.00it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [01:01<07:07, 61.02s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.54it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.45it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.78it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Evaluación Matriz:  25%|██▌       | 2/8 [02:05<06:18, 63.03s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.93it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:30<02:05, 31.47s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.17it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:53<00:43, 21.99s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.82it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.01it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:55<00:31, 31.95s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.96it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:03<00:00, 37.89s/it]

  ✓ Completada en 303.3s (5.05 min)

=======================================================
  Iteración 015 de 030 → iteration_015.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.14it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.66it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [00:46<05:25, 46.51s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.50it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.67it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.37it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Evaluación Matriz:  25%|██▌       | 2/8 [01:53<05:50, 58.39s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.08it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:15<01:55, 28.84s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.59it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:42<00:42, 21.45s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.09it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 31

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.70it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:34<00:29, 29.26s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.55it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:12<00:00, 31.55s/it]

  ✓ Completada en 252.6s (4.21 min)

=======================================================
  Iteración 016 de 030 → iteration_016.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.48it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.63it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:57<06:39, 57.05s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.57it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.14it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:12<06:47, 67.97s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:34<02:09, 32.32s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.42it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 34

Evaluación Matriz:  75%|███████▌  | 6/8 [02:58<00:45, 22.56s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.88it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.13it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Evaluación Matriz:  88%|████████▊ | 7/8 [03:45<00:28, 28.80s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.13it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:22<00:00, 32.77s/it]

  ✓ Completada en 262.4s (4.37 min)

=======================================================
  Iteración 017 de 030 → iteration_017.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.05it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [00:44<05:10, 44.36s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.90it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.83it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.85it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  25%|██▌       | 2/8 [01:52<05:51, 58.52s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.79it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:13<01:53, 28.43s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.32it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 34

Evaluación Matriz:  75%|███████▌  | 6/8 [02:44<00:44, 22.18s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.92it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.09it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [03:33<00:28, 28.90s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.13it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:30<00:00, 33.80s/it]

  ✓ Completada en 270.6s (4.51 min)

=======================================================
  Iteración 018 de 030 → iteration_018.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm
✓ Retrieval completado para embedding: nomic

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.25it/s]

Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.37it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [01:30<10:33, 90.54s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.14it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.75it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

Procesando embeddings:  50%|█████     | 1/2 [00:00<00:00,  6.82it/s]

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.92it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:45<08:09, 81.62s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.83it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [03:13<02:36, 39.07s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.36it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [03:38<00:53, 26.52s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.09it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [04:56<00:39, 39.58s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.42it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:32<00:00, 41.54s/it]

  ✓ Completada en 332.5s (5.54 min)

=======================================================
  Iteración 019 de 030 → iteration_019.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.91it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.57it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  12%|█▎        | 1/8 [00:50<05:55, 50.85s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.78it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.65it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 36

Evaluación Matriz:  25%|██▌       | 2/8 [02:09<06:42, 67.16s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.93it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:33<02:10, 32.67s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.80it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [03:00<00:46, 23.44s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.46it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 36

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.97it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [04:00<00:32, 32.85s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.30it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:40<00:00, 35.05s/it]

  ✓ Completada en 280.6s (4.68 min)

=======================================================
  Iteración 020 de 030 → iteration_020.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.16it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [00:57<06:41, 57.35s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.89it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.30it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.31it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Evaluación Matriz:  25%|██▌       | 2/8 [02:01<06:06, 61.12s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.97it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:22<01:58, 29.51s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.52it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:46<00:42, 21.16s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.36it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.26it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:48<00:31, 31.49s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.81it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:38<00:00, 34.75s/it]

  ✓ Completada en 278.2s (4.64 min)

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.69it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.16it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [01:10<08:15, 70.80s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.33it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.90it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 31

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.01it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 36

Evaluación Matriz:  25%|██▌       | 2/8 [02:29<07:31, 75.23s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:59<02:29, 37.48s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.31it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [03:21<00:49, 24.96s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.48it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.34it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [04:23<00:34, 34.44s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.79it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:08<00:00, 38.52s/it]

  ✓ Completada en 308.3s (5.14 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.45it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:56<06:34, 56.38s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.89it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 31

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.79it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:06<06:25, 64.31s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.82it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:30<02:05, 31.45s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.10it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [03:00<00:47, 23.73s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.18it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.38it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:52<00:31, 31.01s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.97it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:28<00:00, 33.51s/it]

  ✓ Completada en 268.2s (4.47 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.57it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:41<04:53, 41.86s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.77it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.05it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.41it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Evaluación Matriz:  25%|██▌       | 2/8 [01:56<06:08, 61.35s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.09it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 27

Evaluación Matriz:  50%|█████     | 4/8 [02:19<01:59, 29.97s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.67it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:43<00:42, 21.47s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.26it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.63it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:50<00:32, 32.96s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.73it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:40<00:00, 35.10s/it]

  ✓ Completada en 281.0s (4.68 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.92it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.84it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:38<04:32, 38.96s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.37it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 31

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.94it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  25%|██▌       | 2/8 [01:47<05:36, 56.08s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.15it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:09<01:51, 27.86s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:34<00:41, 20.69s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.86it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.58it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:54<00:35, 35.75s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:27<00:00, 33.43s/it]

  ✓ Completada en 267.6s (4.46 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.71it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.27it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  12%|█▎        | 1/8 [01:10<08:10, 70.11s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.27it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.88it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.86it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:20<07:01, 70.26s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.25it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:43<02:14, 33.53s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.21it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 34

Evaluación Matriz:  75%|███████▌  | 6/8 [03:07<00:46, 23.38s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.89it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.01it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [04:17<00:35, 35.13s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.05it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:54<00:00, 36.79s/it]

  ✓ Completada en 294.5s (4.91 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.54it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.28it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:38<04:27, 38.21s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.09it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.60it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.61it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [01:42<05:19, 53.31s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.31it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:00<01:43, 25.76s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.52it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:23<00:37, 18.88s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.57it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.27it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [03:25<00:29, 29.71s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.96it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:01<00:00, 30.22s/it]

  ✓ Completada en 241.9s (4.03 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.18it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.46it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:45<05:17, 45.32s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.39it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.05it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.42it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [01:49<05:37, 56.24s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.21it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:25<02:09, 32.32s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.06it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:48<00:45, 22.54s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.44it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.26it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [03:47<00:31, 31.64s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 49

Evaluación Matriz: 100%|██████████| 8/8 [04:16<00:00, 32.00s/it]

  ✓ Completada en 256.2s (4.27 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.41it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.82it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [01:09<08:07, 69.58s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.95it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.10it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.07it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:04<06:04, 60.74s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:35<02:10, 32.54s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.77it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:59<00:45, 22.74s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.08it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.04it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [03:47<00:29, 29.25s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.21it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:20<00:00, 32.58s/it]

  ✓ Completada en 260.8s (4.35 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.20it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.09it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 29

Evaluación Matriz:  12%|█▎        | 1/8 [00:40<04:46, 40.93s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 33

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.85it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 31

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.14it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 34

Evaluación Matriz:  25%|██▌       | 2/8 [01:53<05:55, 59.29s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.67it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:13<01:53, 28.39s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.17it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:37<00:41, 20.77s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.26it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.04it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [03:46<00:32, 32.89s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:43<00:00, 35.47s/it]

  ✓ Completada en 283.9s (4.73 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.84it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 25
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:01<00:00,  1.98it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Evaluación Matriz:  12%|█▎        | 1/8 [00:46<05:23, 46.26s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.30it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 26

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:01<00:00,  1.96it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 30

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [01:47<05:31, 55.33s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 24

Evaluación Matriz:  50%|█████     | 4/8 [02:10<01:51, 27.84s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.66it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  75%|███████▌  | 6/8 [02:32<00:39, 19.73s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.88it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 32

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.83it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  88%|████████▊ | 7/8 [03:37<00:31, 31.30s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.10it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:08<00:00, 31.02s/it]

  ✓ Completada en 248.3s (4.14 min)

Todas las iteraciones completadas.

In [12]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

print("\nEstadísticas por matriz:")
display(df_stats)

with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 10
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,10,50.00,0.00,23.66,76.34
1,Matriz 2,10,66.67,0.00,36.78,87.30
2,Matriz 4,10,90.00,31.62,59.58,98.21
3,Matriz 6,10,100.00,0.00,72.25,100.00
4,Matriz 7,10,30.00,25.82,10.78,60.32
5,Matriz 8,10,100.00,0.00,72.25,100.00
6,Total (matrices evaluadas),10,65.00,7.07,35.37,86.31

✓ Estadísticas exportadas → AsyncMultiQuery_TSF_STD_Statistics.xlsx

In [6]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

print("\nEstadísticas por matriz:")
display(df_stats)

with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,50.00,0.00,33.15,66.85
1,Matriz 2,30,66.67,0.00,48.78,80.77
2,Matriz 4,30,76.67,43.02,59.07,88.21
3,Matriz 6,30,100.00,0.00,88.65,100.00
4,Matriz 7,30,23.33,25.37,11.79,40.93
5,Matriz 8,30,100.00,0.00,88.65,100.00
6,Total (matrices evaluadas),30,62.33,7.28,44.55,77.32

✓ Estadísticas exportadas → AsyncMultiQuery_TSF_STD_Statistics.xlsx

### **1.4 Tailing Embankments (TE)**

1hora 10 iteraciones.

In [6]:
N_ITERATIONS = 10

OUTPUT_FOLDER = "AsyncMultiQuery_TSF_TE_Evaluation"

PATH_GROUND_TRUTH = "../src/evaluation_rag/rag_ground_truth/04_TE_Embalse_GT.xlsx"

CONFIDENCE   = 0.95
OUTPUT_STATS = "AsyncMultiQuery_TSF_TE_Statistics.xlsx"

def get_last_iteration(folder: Path) -> int:
    if not folder.exists():
        return 0
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    numbers = []
    for f in folder.iterdir():
        match = pattern.match(f.name)
        if match:
            numbers.append(int(match.group(1)))
    return max(numbers) if numbers else 0


def parse_accuracy(value) -> float:
    if isinstance(value, (int, float)):
        v = float(value)
        return v / 100 if v > 1 else v
    cleaned = str(value).replace("%", "").strip()
    try:
        v = float(cleaned)
        return v / 100 if v > 1 else v
    except ValueError:
        return float("nan")


def load_iteration(path: Path) -> dict:
    xl = pd.read_excel(path, sheet_name="resultado final")
    xl.columns = xl.columns.str.strip()
    result = {}
    for _, row in xl.iterrows():
        matriz = str(row["Matriz"]).strip()
        acc    = parse_accuracy(row["Accuracy"])
        result[matriz] = acc
    return result


def get_iteration_files(folder: Path) -> list:
    pattern = re.compile(r"iteration_(\d+)\.xlsx$", re.IGNORECASE)
    files = []
    for f in folder.iterdir():
        if pattern.match(f.name):
            files.append(f)
    return sorted(files, key=lambda f: int(pattern.match(f.name).group(1)))


def wilson_ci(p: float, n: int, confidence: float = 0.95) -> tuple:
    if n == 0 or np.isnan(p):
        return (float("nan"), float("nan"))
    z           = stats.norm.ppf(1 - (1 - confidence) / 2)
    denominator = 1 + z**2 / n
    centre      = (p + z**2 / (2 * n)) / denominator
    margin      = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denominator
    lower = max(0.0, centre - margin)
    upper = min(1.0, centre + margin)
    return (lower, upper)

embedding_configs = [
    EmbeddingConfig(
        name="minilm",
        embedding_type="huggingface",
        model_name="sentence-transformers/all-MiniLM-L6-v2",
        path_vector_storage="../src/evaluation_retrieval/vector_storage/04_enami_embalse/04_enami_all_mini_L6_v2"
    ),
    EmbeddingConfig(
        name="nomic",
        embedding_type="nomic",
        model_name="nomic-embed-text-v1.5",
        path_vector_storage="../src/evaluation_retrieval/vector_storage/04_enami_embalse/04_enami_nomic"
    )
]

pipeline_rag = AsyncMultiEmbeddingRAGV2(
    embedding_configs=embedding_configs,
    top_k=13,
    top_n=5
)

llm_evaluador = LLMEvaluator()

folder = Path(OUTPUT_FOLDER)
folder.mkdir(parents=True, exist_ok=True)

last  = get_last_iteration(folder)
start = last + 1
end   = last + N_ITERATIONS

print(f"Iteraciones previas encontradas : {last}")
print(f"Corriendo iteraciones           : {start} → {end}")
print(f"Carpeta de salida               : {folder.resolve()}\n")

for i in range(start, end + 1):
    name_excel = folder / f"iteration_{i:03d}.xlsx"
    print(f"{'='*55}")
    print(f"  Iteración {i:03d} de {end:03d} → {name_excel.name}")
    print(f"{'='*55}")

    inicio = time.time()

    auto_evaluation_rag_v2(
        path_ground_truth=PATH_GROUND_TRUTH,
        name_excel=str(name_excel),
        pipeline_rag=pipeline_rag,
        llm_evaluador=llm_evaluador,
    )

    elapsed = time.time() - inicio
    print(f"  ✓ Completada en {elapsed:.1f}s ({elapsed/60:.2f} min)\n")

print("Todas las iteraciones completadas.")

Configurando modelos de embeddings e índices...
Configurando embedding: minilm
✓ Embedding minilm configurado correctamente
Configurando embedding: nomic
✓ Embedding nomic configurado correctamente
Cargando Cross-Encoder...
Iteraciones previas encontradas : 20
Corriendo iteraciones           : 21 → 30
Carpeta de salida               : C:\Users\gol_m\OneDrive\Desktop\eswa\experiments\AsyncMultiQuery_TSF_TE_Evaluation

=======================================================
  Iteración 021 de 030 → iteration_021.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:01<00:00,  1.92it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:31<03:42, 31.75s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.94it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.51it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.76it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.33it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  25%|██▌       | 2/8 [02:23<07:52, 78.81s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.67it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:47<02:27, 36.77s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.42it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:29<00:59, 29.51s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.96it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.60it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [04:29<00:37, 37.24s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.01it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:05<00:00, 38.25s/it]

  ✓ Completada en 306.5s (5.11 min)

=======================================================
  Iteración 022 de 030 → iteration_022.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.39it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:27<03:14, 27.75s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.93it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.52it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.07it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  25%|██▌       | 2/8 [02:11<07:13, 72.19s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Evaluación Matriz:  50%|█████     | 4/8 [03:02<02:51, 42.95s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.25it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:50<01:08, 34.12s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.46it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.02it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  88%|████████▊ | 7/8 [05:00<00:43, 43.25s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:33<00:00, 41.70s/it]

  ✓ Completada en 333.8s (5.56 min)

=======================================================
  Iteración 023 de 030 → iteration_023.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:01<00:00,  1.73it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:34<04:00, 34.31s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.34it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.69it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 50

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.52it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.41it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  25%|██▌       | 2/8 [02:26<08:02, 80.36s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.08it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [03:09<02:53, 43.35s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.41it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:55<01:07, 33.63s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.85it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.04it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [05:12<00:44, 44.70s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.11it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:54<00:00, 44.32s/it]

  ✓ Completada en 354.7s (5.91 min)

=======================================================
  Iteración 024 de 030 → iteration_024.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.62it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:29<03:24, 29.22s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.86it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.33it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.01it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 39

Evaluación Matriz:  25%|██▌       | 2/8 [02:19<07:42, 77.13s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

Procesando embeddings:  50%|█████     | 1/2 [00:00<00:00,  6.64it/s]

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.63it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:51<02:35, 38.83s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.68it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  75%|███████▌  | 6/8 [03:39<01:03, 31.60s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.43it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 42

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.81it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  88%|████████▊ | 7/8 [05:04<00:45, 45.19s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.30it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:42<00:00, 42.77s/it]

  ✓ Completada en 342.3s (5.70 min)

=======================================================
  Iteración 025 de 030 → iteration_025.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.65it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:27<03:15, 27.94s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 45

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.46it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.62it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.56it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:20<07:46, 77.77s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.86it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:57<02:42, 40.61s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.13it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:38<01:02, 31.02s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.41it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.71it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  88%|████████▊ | 7/8 [05:00<00:43, 43.94s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.07it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Evaluación Matriz: 100%|██████████| 8/8 [05:34<00:00, 41.87s/it]

  ✓ Completada en 335.1s (5.59 min)

=======================================================
  Iteración 026 de 030 → iteration_026.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.08it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:30<03:33, 30.49s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.10it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.12it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.30it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  25%|██▌       | 2/8 [02:50<09:28, 94.77s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.29it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [03:28<03:09, 47.33s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.20it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Evaluación Matriz:  75%|███████▌  | 6/8 [04:06<01:07, 33.98s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.03it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 42

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.06it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 39

Evaluación Matriz:  88%|████████▊ | 7/8 [05:07<00:40, 40.83s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.44it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:44<00:00, 43.02s/it]

  ✓ Completada en 344.4s (5.74 min)

=======================================================
  Iteración 027 de 030 → iteration_027.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.49it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 42

Evaluación Matriz:  12%|█▎        | 1/8 [00:38<04:26, 38.03s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.03it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.30it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.66it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.35it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 41

Evaluación Matriz:  25%|██▌       | 2/8 [02:27<07:59, 79.88s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.11it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:51<02:29, 37.41s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.05it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:22<00:54, 27.03s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.86it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 42

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.93it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Evaluación Matriz:  88%|████████▊ | 7/8 [04:25<00:36, 36.16s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.26it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:02<00:00, 37.80s/it]

  ✓ Completada en 302.6s (5.04 min)

=======================================================
  Iteración 028 de 030 → iteration_028.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.79it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:26<03:07, 26.86s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.63it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 38

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.06it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 37

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.77it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  25%|██▌       | 2/8 [02:14<07:26, 74.46s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.45it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:41<02:25, 36.27s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.80it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:12<00:52, 26.33s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.21it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.16it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  88%|████████▊ | 7/8 [04:20<00:36, 36.98s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.50it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:51<00:00, 36.44s/it]

  ✓ Completada en 291.7s (4.86 min)

=======================================================
  Iteración 029 de 030 → iteration_029.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.53it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:26<03:02, 26.13s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.86it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 45

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.48it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.16it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 39

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.99it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  25%|██▌       | 2/8 [02:03<06:46, 67.80s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.76it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Evaluación Matriz:  50%|█████     | 4/8 [02:37<02:23, 35.92s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.18it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:07<00:52, 26.13s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.90it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.52it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  88%|████████▊ | 7/8 [04:21<00:38, 38.29s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.14it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [04:52<00:00, 36.57s/it]

  ✓ Completada en 292.7s (4.88 min)

=======================================================
  Iteración 030 de 030 → iteration_030.xlsx
=======================================================

Evaluación Matriz:   0%|          | 0/8 [00:00<?, ?it/s]

Matriz 1
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.43it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  12%|█▎        | 1/8 [00:28<03:20, 28.71s/it]

Matriz 2
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  2.29it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 45

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.31it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 43

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.28it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 39

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.82it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 35

Evaluación Matriz:  25%|██▌       | 2/8 [02:16<07:31, 75.30s/it]

Matriz 3 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 4
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  5.22it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 28

Evaluación Matriz:  50%|█████     | 4/8 [02:52<02:37, 39.31s/it]

Matriz 5 — EXCLUIDA (sin datos de control operacional periódico)
Matriz 6
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.82it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 44

Evaluación Matriz:  75%|███████▌  | 6/8 [03:23<00:55, 27.97s/it]

Matriz 7
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  4.44it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 47

Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:03<00:00,  1.58s/it]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 40

Evaluación Matriz:  88%|████████▊ | 7/8 [04:35<00:39, 39.30s/it]

Matriz 8
Iniciando retrieval con múltiples embeddings...

✓ Retrieval completado para embedding: minilm

Procesando embeddings: 100%|██████████| 2/2 [00:00<00:00,  3.89it/s]

✓ Retrieval completado para embedding: nomic
Agregando y filtrando nodos de todos los embeddings...
Procesando nodos de embedding: minilm
Procesando nodos de embedding: nomic
Total de nodos antes del filtrado: 130
Total de nodos después del filtrado: 46

Evaluación Matriz: 100%|██████████| 8/8 [05:05<00:00, 38.18s/it]

  ✓ Completada en 305.6s (5.09 min)

Todas las iteraciones completadas.

In [3]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

print("\nEstadísticas por matriz:")
display(df_stats)

with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 10
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,10,100.0,0.00,72.25,100.00
1,Matriz 2,10,75.0,0.00,44.22,91.91
2,Matriz 4,10,10.0,31.62,1.79,40.42
3,Matriz 6,10,0.0,0.00,0.00,27.75
4,Matriz 7,10,25.0,26.35,8.09,55.78
5,Matriz 8,10,90.0,31.62,59.58,98.21
6,Total (matrices evaluadas),10,55.0,7.07,27.37,79.86

✓ Estadísticas exportadas → AsyncMultiQuery_TSF_TE_Statistics.xlsx

In [5]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

print("\nEstadísticas por matriz:")
display(df_stats)

with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 20
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,20,100.0,0.00,83.89,100.00
1,Matriz 2,20,75.0,0.00,53.13,88.81
2,Matriz 4,20,30.0,47.02,14.55,51.90
3,Matriz 6,20,0.0,0.00,0.00,16.11
4,Matriz 7,20,27.5,25.52,12.84,49.41
5,Matriz 8,20,95.0,22.36,76.39,99.11
6,Total (matrices evaluadas),20,58.0,8.34,36.86,76.56

✓ Estadísticas exportadas → AsyncMultiQuery_TSF_TE_Statistics.xlsx

In [7]:
folder = Path(OUTPUT_FOLDER)
files  = get_iteration_files(folder)

print(f"Archivos encontrados: {len(files)}")
for f in files:
    print(f"  {f.name}")

iterations_data = {}
for f in files:
    label = f.stem
    try:
        iterations_data[label] = load_iteration(f)
    except Exception as e:
        print(f"  ⚠ Error leyendo {f.name}: {e}")

all_matrices = []
for data in iterations_data.values():
    for m in data.keys():
        if m not in all_matrices:
            all_matrices.append(m)

detail_rows = []
for matriz in all_matrices:
    row = {"Matriz": matriz}
    for label, data in iterations_data.items():
        row[label] = data.get(matriz, float("nan"))
    detail_rows.append(row)

df_detail = pd.DataFrame(detail_rows)
iter_cols  = list(iterations_data.keys())

stats_rows = []
for _, row in df_detail.iterrows():
    values        = row[iter_cols].values.astype(float)
    values        = values[~np.isnan(values)]
    n             = len(values)
    mean          = np.mean(values) if n > 0 else float("nan")
    std           = np.std(values, ddof=1) if n > 1 else float("nan")
    ci_low, ci_up = wilson_ci(mean, n, CONFIDENCE)

    stats_rows.append({
        "Matriz":                           row["Matriz"],
        "N iteraciones":                    n,
        "Media (%)":                        round(mean   * 100, 2),
        "Std (%)":                          round(std    * 100, 2) if not np.isnan(std) else float("nan"),
        f"CI_lower {int(CONFIDENCE*100)}%": round(ci_low * 100, 2),
        f"CI_upper {int(CONFIDENCE*100)}%": round(ci_up  * 100, 2),
    })

df_stats = pd.DataFrame(stats_rows)

df_detail_pct = df_detail.copy()
for col in iter_cols:
    df_detail_pct[col] = df_detail_pct[col].apply(
        lambda x: f"{x*100:.2f}%" if not np.isnan(x) else "N/A"
    )

print("\nEstadísticas por matriz:")
display(df_stats)

with pd.ExcelWriter(OUTPUT_STATS, engine="openpyxl") as writer:
    df_detail_pct.to_excel(writer, sheet_name="Detalle",      index=False)
    df_stats.to_excel(     writer, sheet_name="Estadísticas", index=False)

print(f"\n✓ Estadísticas exportadas → {OUTPUT_STATS}")

Archivos encontrados: 30
  iteration_001.xlsx
  iteration_002.xlsx
  iteration_003.xlsx
  iteration_004.xlsx
  iteration_005.xlsx
  iteration_006.xlsx
  iteration_007.xlsx
  iteration_008.xlsx
  iteration_009.xlsx
  iteration_010.xlsx
  iteration_011.xlsx
  iteration_012.xlsx
  iteration_013.xlsx
  iteration_014.xlsx
  iteration_015.xlsx
  iteration_016.xlsx
  iteration_017.xlsx
  iteration_018.xlsx
  iteration_019.xlsx
  iteration_020.xlsx
  iteration_021.xlsx
  iteration_022.xlsx
  iteration_023.xlsx
  iteration_024.xlsx
  iteration_025.xlsx
  iteration_026.xlsx
  iteration_027.xlsx
  iteration_028.xlsx
  iteration_029.xlsx
  iteration_030.xlsx

Estadísticas por matriz:

,Matriz,N iteraciones,Media (%),Std (%),CI_lower 95%,CI_upper 95%
0,Matriz 1,30,100.00,0.00,88.65,100.00
1,Matriz 2,30,75.00,0.00,57.30,87.02
2,Matriz 4,30,26.67,44.98,14.18,44.45
3,Matriz 6,30,0.00,0.00,0.00,11.35
4,Matriz 7,30,25.00,25.43,12.98,42.70
5,Matriz 8,30,96.67,18.26,83.33,99.41
6,Total (matrices evaluadas),30,57.33,7.85,39.82,73.19

✓ Estadísticas exportadas → AsyncMultiQuery_TSF_TE_Statistics.xlsx